---
title: "My Mastodon Analytics for 2020"
author: "akela"
output: html_document
---

```{r setup, warning = FALSE, message=FALSE}
knitr::opts_chunk$set(
	fig.align = "center",
	fig.pos = "h",
	message = FALSE,
	warning = FALSE,
	out.width = "90%",
	dpi = 300
)

library(dplyr)
library(stringr)

library(ggplot2)
library(ggrepel)
library(ggtext)
library(ggnetwork)
library(igraph)
library(ggimage)
library(grid)
library(gridExtra)
library(RColorBrewer)
library(extrafont)

library(forcats)
library(lubridate)
library(zoo)
library(tidyr)

library(rjson)


loadfonts()

frank_med <- "Franklin Gothic Medium Cond"

ggthemr::ggthemr("flat dark", text_size = 11)
pal <- c('#3498db', '#2ecc71', '#f1c40f')
col_bkground <- '#34495e'
col_text <- '#dfe6ed'
col_text2 <- '#f7f9fa'

newtheme <- theme(
  text = element_text(family = frank_med),
  plot.title = element_text(size = 10, face = "plain", color = "white"),
  plot.background = element_blank(),
  legend.position = "right",
  legend.box.margin = margin(5, 0, 5, 5),
  legend.text = element_text(color = col_text),
  legend.background = element_blank(),
  legend.key = element_rect(color = NA),
  panel.grid.major.x = element_blank(),
  panel.spacing = unit(0, "mm"),
  axis.ticks = element_line(color = col_text),
  axis.title = element_text(size = 8, color = col_text),
  axis.text = element_text(color = col_text))

newtheme_void <- theme_void(base_family = frank_med) +
  theme(legend.position = "none",
        plot.background = element_blank(),
        plot.title = element_text(size = 10, face = "plain", color = "white"))

update_geom_defaults("text", list(family = frank_med, size = 2.7, color = col_text))
update_geom_defaults("richtext", list(family = frank_med, size = 2.7, color = col_text))
update_geom_defaults("text_repel", list(family = frank_med, size = 2.7, color = col_text))

custom_palette <- brewer.pal(3, "Set2")
```


```{r load-data}
mstdn_data <- fromJSON(file = "outbox.json")
mstdn_data <- mstdn_data$orderedItems

load("kwords.RData")
```

```{r functions}
chr0_to_NA <- function(x) {
  if(length(x) == 0) {NA} else {x}}

get_id <- function(x) {
  str_extract(x, "(?<=statuses\\/)[0-9]+(?=\\/?)")
}

span <- function(x, color) {
  paste0("<span style='color:", color, "'>", x, "</span>")
}
```


```{r data-cleaning}
mstdn_data_df <- lapply(mstdn_data, function(x) {
  if(x$type == "Announce") {content = ""; id_inReplyTo = NA}
  else {content = x$object$content
        id_inReplyTo = get_id(x$object$inReplyTo) %>% chr0_to_NA}
  
  if("summary" %in% names(x$object)) {summary <- chr0_to_NA(x$object$summary)}
  else {summary <- NA}
  
  data.frame(published = x$published,
             id = get_id(x$id),
             content = content,
             summary = summary,
             id_inReplyTo = id_inReplyTo)
  })%>%
  do.call(rbind, .)%>%
  mutate(published = as.POSIXct(published, format = "%Y-%m-%dT%H:%M:%OSZ", tz = "UTC")%>%
           format(tz = Sys.timezone()),
         date = as.Date(published),
         time = hour(published),
         type = case_when(content == "" ~ "Boost",
                          str_detect(content, "\\@") ~ "Reply",
                          TRUE ~ "Original Toot")%>%
           factor(levels = c("Original Toot", "Reply", "Boost")))%>%
  mutate(is_weekend = ifelse(weekdays(date) %in% c("Saturday", "Sunday"), 
                             "Weekend", "Weekday"))%>%
  mutate(content = str_remove_all(content, "<.*?>|&amp;"),
         word_count = nchar(str_remove_all(content, "@\\S+\\s"))+ 
                              ifelse(is.na(summary), 0, nchar(summary)))


emoji_hashtag_df <- lapply(mstdn_data, function(toot) {
  
  if(toot$type == "Announce") {return(NULL)}
  tag_list <- toot$object$tag
  
  if(length(tag_list) == 0) {return(NULL)}
  else {
    data.frame(name = names(unlist(tag_list)),
               value = unlist(tag_list))%>%
      filter(name %in% c("type", "name", "icon.url"))%>%
      mutate(id = get_id(toot$id))
  }})%>%
  do.call(rbind, .) %>% 
  mutate(group = findInterval(1:n(), which(name == "type")))%>%
  group_by(group) %>%
  filter(any(value %in% c("Emoji", "Hashtag")))%>% 
  pivot_wider() %>% ungroup() %>% select(-group)
```


```{r, fig.width = 2.3, fig.height = 2.3}
edges <- mstdn_data_df %>%
  filter(!is.na(id_inReplyTo), 
         id_inReplyTo %in% mstdn_data_df$id)%>%
  select(id_inReplyTo, id)%>%
  rename("from" = "id_inReplyTo", "to" = "id")%>%
  arrange(from)%>%
  mutate(color = row_number())

nodes <- data.frame(id = unique(unlist(edges %>% select(from, to))))
routes_igraph <- graph_from_data_frame(d = edges, vertices = nodes, directed = TRUE)

# Ref: https://stackoverflow.com/a/44484419
sub_gs <- components(routes_igraph)$membership
small_sub <- names(which(table(sub_gs) < 4))%>%as.numeric
rm_nodes <- names(sub_gs[which(sub_gs %in% small_sub)])
routes_igraph2 <- delete_vertices(routes_igraph, rm_nodes)
sub_gs2 <- components(routes_igraph2)$membership

set.seed(1)

network_df <- ggnetwork(routes_igraph2)%>%
  merge(data.frame(name = names(sub_gs2),
                   value = unname(sub_gs2)), by = "name",
        all.x = TRUE)
  

nodetext <- network_df %>%
  group_by(value)%>%
  mutate(n_toot = ceiling(n()/2))%>%
  arrange(name)%>%
  slice(round(n()/2))%>% 
  cbind(label = c("WSC", "Chess", "Comet", "COVID-19", "GQ\n",
                   "CoH", "snow", "MMAL", "Tuor", "L5Y", 
                  "Ars Nova", "star", "movie"))%>%
  mutate(label = paste0(label, " (", n_toot, ")"))



p_network <- 
  network_df %>%
  mutate(value = value %% 4)%>%
  ggplot(aes(x = x, xend = xend + (xend - x)*0.3,
             y = y, yend = yend + (yend - y)*0.3)) +
  geom_edges(arrow = arrow(length = unit(1.5, "pt"), type = "open",
                           angle = 40),
             color = "#c5d7e8", size = 0.3) +
  geom_nodes(aes(colour = as.factor(value)), size = 0.8)+
  geom_nodetext(data = nodetext,
                aes(x = x + (x-0.5)*0.25, y = y + (y-0.5)*0.2,
                    label = label, color = as.factor(value %% 4)), 
                size = 2.5, lineheight = 0.8,
                nudge_x = c(-0.2, -0.15, -0.12, 0.05, -0.1,
                            0.15, -0.2, 0.1, 0, -0.1,
                            0.28, -0.22, -0.2),
                nudge_y = c(-0.04, -0.06, 0.06, -0.2, 0.1,
                            0.02, -0.16, -0.13, -0.3, -0.05,
                            -0.05, 0.07, -0.02),
                angle = c(30, 0, 35, 60, 0,
                          50, -45, 20, -45, 0,
                          -60, 0, 0))+
  labs(title = "Toot Threads")+
  scale_color_manual(values = c('#30a7fc', pal[-1], 'salmon2', "purple"))+
  newtheme_void+
  theme(aspect.ratio = 1)
```

```{r toots-by-date, fig.width = 7, fig.height = 2.8}
date_df <- mstdn_data_df %>%
  group_by(date, is_weekend) %>%
  mutate(n = n()) %>% slice(1) %>% ungroup%>%
  mutate(n_7dayavg = rollmean(n, k = 7, na.pad = TRUE)) 

date_text_df <- date_df %>% select(date, n) %>% ungroup()%>% 
  filter(row_number() == 1 | n == max(date_df$n))%>% group_by(date) %>% slice(1)%>%
  mutate(label = paste0("(", month(date, label = TRUE), " ", day(date), ")"))%>%
  mutate(label = ifelse(n == max(date_df$n), paste(n, label),
                        paste0("Joined ", label, "\n\u2193")))


p_date <- date_df %>%
  ggplot(aes(x = date, y = n)) +
  geom_col(aes(fill = is_weekend), color = col_bkground, size = 0.2)+
  geom_line(aes(color = "7 Day Average", y = n_7dayavg), size = 0.6)+
  geom_text(data = date_text_df,
            aes(y = n + c(5, 1), label = label), size = 2.4,
            hjust = c(0, 0.08), lineheight = 0.8, nudge_x = c(-1, 0))+
  scale_x_date(expand = expansion(add = c(1, 1)), date_labels = "%b %Y")+
  scale_y_continuous(expand = expansion(mult = c(0, 0.03)))+
  scale_color_manual(values = "lightblue1", name = NULL)+
  labs(x = NULL, y = NULL, title = "No. of Toots by Date")+
  guides(fill = guide_legend(keywidth = 0.6, keyheight = 0.6, order = 1),
         color = guide_legend(keywidth = 0.7, keyheight = 0.6, order = 2))+
  newtheme +
  theme(legend.position = c(0.5, 0.8),
        legend.spacing = unit(0, "mm"),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.box = "horizontal",
        legend.direction = "horizontal",
        axis.line.x = element_line(color = col_text),
        axis.line.y = element_blank())
```

```{r word-count, fig.width = 7, fig.height = 2.8}
rant_index <- 123
hurin_index <- c(str_which(mstdn_data_df$content, "Children of Húrin"),
                 str_which(mstdn_data_df$summary, "Children of Húrin"))
gq_index <- str_which(mstdn_data_df$summary, "Ghost Quartet: in Concert, Crow’s Theatre")[2]
l5y_index <- str_which(mstdn_data_df$summary, "The Last Five Years, Southwark")[1]

note_df <- data.frame(x = c(rant_index, min(hurin_index), gq_index, l5y_index),
                      y = 420,
                      label = c("Rant", "CoH Notes", "Ghost Quartet:\nin Concert",
                                "L5Y, Southwark\nPlayhouse"),
                      hjust = c(1, 1, 0, 1))

p_wordcount <- mstdn_data_df %>%
  ggplot(aes(x = 1:nrow(mstdn_data_df), y = word_count)) +
  geom_rect(data = data.frame(xmin = min(hurin_index), xmax = max(hurin_index),
                              ymin = 0, ymax = max(mstdn_data_df$word_count)*1.02),
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "white", alpha = 0.15, inherit.aes = FALSE)+
  geom_col(color = NA)+
  geom_text_repel(data = note_df, aes(x = x, y = y, label = label, 
                                      hjust = hjust),
                  inherit.aes = FALSE, vjust = 1, lineheight = 0.8, 
                  family = "Franklin Gothic Medium Cond",
                  direction="y", hjust = 0,
                  nudge_x = c(-40, -60, 30, 20),
                  nudge_y = c(10, 20, 30, 30), min.segment.length = 0.01,
                  segment.color = col_text)+
  scale_x_continuous(expand = expansion(add = c(2, 2)), 
                     breaks = seq(200, 1000, 200),
                     labels = function(x) paste0(x, "th Toot"))+
  scale_y_continuous(expand = expansion(mult = c(0, 0)))+
  labs(x = NULL, y = NULL, title = "Toot Length in Characters")+
  guides(fill = guide_legend(keywidth = 0.8, keyheight = 0.8, order = 1),
         color = guide_legend(keywidth = 0.8, keyheight = 0.8, order = 2))+
  newtheme +
  theme(legend.position = "bottom",
        axis.line.x = element_line(color = col_text),
        axis.line.y = element_blank())


p_dist_wordcount <- mstdn_data_df %>%
  ggplot(aes(y = word_count),)+
  geom_histogram(aes(x = ..density..), bins = 20, 
                 color = col_bkground, size = 0.4)+
  scale_x_continuous(expand = expansion(mult = c(0.02, 0.07)))+
  scale_y_continuous(expand = expansion(add = c(0.3, 0.3)))+
  labs(title = " ", y = NULL, x = NULL)+
  newtheme +
  theme(axis.text.x = element_text(color = NA),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.grid = element_blank())
```

```{r toots-by-type, fig.width=2, fig.height=2}
p_type <- mstdn_data_df %>%
  group_by(type)%>%
  summarise(n = n())%>%
  mutate(prop = round(n/nrow(mstdn_data_df) * 100, 0),
         xpos = ifelse(prop <= 15, 1.9, 1))%>%
  ggplot(aes(x = 1, y = n, fill = type, group = type))+
  geom_col(width = 1, color = col_bkground, size = 0.8) +
  geom_text(aes(x = xpos, color = type, 
                label = paste0(type,  "\n", n, " (", prop, "%)")), 
            lineheight = 1, 
            position = position_stack(vjust = 0.7),
            show.legend = FALSE, size = 2.7)+
  geom_segment(aes(x = 1.5, xend = 1.6, y = 40, yend = 42),
              color = "white", inherit.aes = FALSE)+
  scale_color_manual(values = c("white", col_bkground, "white"))+
  coord_polar("y", start = 0) +
  guides(fill = guide_legend(keywidth = 0.9, keyheight = 0.9, title = NULL))+
  newtheme_void + theme(plot.margin = margin(-15, -15, -25, -15))
```

```{r toots-by-time, fig.width=6, fig.height=3}
time_df <- mstdn_data_df %>%
  group_by(time, type) %>%
  summarise(n = n()) %>% 
  group_by(time) %>%
  mutate(n_total = sum(n))


p_time <- time_df %>%
  ggplot(aes(x = as.numeric(time), y = n, fill = forcats::fct_rev(type))) +
  geom_col(color = col_bkground, alpha = 0.9, size = 0.4, width = 0.9)+
  geom_text(aes(label = n_total, y = n_total + 1), vjust = 0, 
            show.legend = FALSE, size = 2.5)+
  scale_x_continuous(breaks = seq(0, 24, 3) - 0.5,
                     labels = function(x) paste0(x+0.5, ":00"),
                     expand = expansion(add = c(0.5, 0.5)))+
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))+
  scale_fill_manual(values = pal, breaks =  c("Original Toot", "Reply", "Boost"))+
  guides(fill = guide_legend(keywidth = 0.6, keyheight = 0.6, title = NULL))+
  labs(x = NULL, y = NULL, title = "No. of Toots by Hour of the Day")+
  newtheme +
  theme(legend.position = "bottom",
        axis.line.x = element_line(color = col_text),
        axis.line.y = element_blank(),
        legend.box.margin = margin(0, 5, 5, 5))
```


```{r plot-emoji, fig.height=2, fig.width=1}
p_emoji <- emoji_hashtag_df %>%
  filter(type == "Emoji")%>%
  group_by(icon.url) %>% 
  summarise(n = n())%>% 
  ungroup() %>% 
  mutate(prop = round(n/sum(emoji_hashtag_df$type == "Emoji") * 100))%>%
  filter(n > 1) %>% arrange(desc(n)) %>% 
  slice(1:min(n(), 5))%>%
  ggplot(aes(x = n, y = fct_reorder(icon.url, n))) +
  geom_col(width = 0.7, fill = pal[3])+
  geom_text(aes(x = n + c(-3, rep(3, 4)), label = paste0(n, " (", prop, "%)"), 
                hjust = c(1, rep(0, 4))),
            color = c(col_bkground, rep("white", 4)))+
  geom_image(aes(x = -5, image = icon.url), size = 0.16, 
             hjust = 1, asp = 1.05)+
  scale_x_continuous(expand = expansion(mult = c(0.3, 0)))+
  scale_y_discrete(expand = expansion(mult = c(0.1, 0.1)))+
  labs(x = NULL, y = NULL, title = "Top 5 Emojis")+
  newtheme +
  theme(axis.text = element_blank(), 
        axis.line = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(hjust = 0),
        axis.ticks = element_blank(),
        panel.border = element_blank())
```

```{r plot-hashtag, fig.width=4, fig.height=2}
p_hashtag <- emoji_hashtag_df %>%
  filter(type == "Hashtag")%>%
  mutate(name = ifelse(nchar(name) >= 8 & (!str_detect(name, "[A-Za-z]+")), 
                       paste(substr(name, 1, round(nchar(name)/2)),
                             substr(name, round(nchar(name)/2)+1, 1E3),
                             sep = "\n"),
                       name))%>%
  group_by(name) %>% 
  summarise(n = n())%>%
  filter(n > 1) %>%
  arrange(desc(n)) %>% slice(1:min(5, n()))%>%
  ggplot(aes(x = n, y = fct_reorder(name, n)))+
  geom_col(width = 0.7) +
  geom_text(aes(x = n + c(-0.1, 0.1, 0.1), label = n, hjust = c(1, 0, 0)),
            color = c(col_bkground, col_text2, col_text2))+
  scale_x_continuous(expand = expansion(mult = c(0, 0.02)))+
  scale_y_discrete(expand = expansion(add = c(0.2, 0.2)))+
  labs(x = NULL, y = NULL, title = "Top 3 Hashtags")+
  newtheme +
  theme(axis.text.y = element_text(size = 8.5, color = col_text2),
        axis.text.x = element_blank(), 
        axis.line = element_blank(),
        panel.grid = element_blank(),
        axis.ticks = element_blank())
```

```{r sondheim}
p_keyword_func <- function(kwords, title_prefix, color = pal[2]) {
  
  kword_df <- mstdn_data_df %>%
    merge(emoji_hashtag_df%>% filter(type == "Hashtag") %>% 
            select(-icon.url), all.x = TRUE)%>%
    group_by(id)%>%
    summarise(content = paste(name, content, summary, collapse = " "))%>%
    merge(data.frame(name = names(sub_gs),
                     value = unname(sub_gs)), 
          by.x = "id", by.y = "name", all.x = TRUE)%>%
    group_by(value) %>%
    mutate(is_kword = str_detect(tolower(content), paste(kwords, collapse = "|")),
           is_kword = any(is_kword))%>%
    ungroup()%>%
    mutate(is_kword = ifelse(is.na(value), str_detect(tolower(content), paste(kwords, collapse = "|")),
                             is_kword))
  
  title <- paste0(title_prefix, "-Related:<br>",
                  span(sum(kword_df$is_kword), color), "  Toots ", 
                  span(paste0("(", round(sum(kword_df$is_kword)/nrow(mstdn_data_df) * 100), "%)"), color))
  
  p1 <- kword_df %>%
    ggplot(aes(x = 1:nrow(mstdn_data_df), y = 500, fill = is_kword))+
    geom_col(color = NA)+
    coord_cartesian(expand = FALSE)+
    scale_x_continuous(expand = expansion(add = c(2, 2)),
                       breaks = NULL, sec.axis = dup_axis(breaks = seq(200, 1000, 200)))+
    scale_fill_manual(values = c(NA, color))+
    labs(x = NULL, y = NULL)+
    newtheme +
    theme(legend.position = "none",
          panel.grid = element_blank(),
          axis.text.x.top = element_blank(),
          axis.text.y = element_text(color = NA),
          axis.ticks.y = element_line(color = NA),
          axis.line = element_blank(),
          panel.background = element_rect(color = NA, fill = '#4f6982'))
  
  p2 <- ggplot()+
    geom_rect(aes(xmin = 0, xmax = 0.5, ymin = -0.05, ymax = 0.05),
              fill = NA)+
    geom_richtext(aes(x = 0, y = 0, label = title), size = 2.7,
                  lineheight = 1.25, hjust = 0, fill = NA, label.color = NA,
                  label.padding = unit(c(0, 0, 0, 0), "mm"))+ 
    coord_cartesian(expand = FALSE)+
    newtheme_void
  
  return(list(p1 = p1, p2 = p2))
}


p_sondheim <- p_keyword_func(sondheim_kwords, "Sondheim")
p_tolkien <- p_keyword_func(tolkien_kwords, "Tolkien", color = pal[3])
p_malloy <- p_keyword_func(malloy_kwords, "Malloysical", color = "salmon2")
```

```{r, fig.width = 7, fig.height = 7.5}
plot_mat <- matrix(c(1, 1, 1, 1, 1, 1, 1, 1, 1,
                     1, 1, 1, 1, 1, 1, 1, 1, 1,
                     1, 1, 1, 1, 1, 1, 1, 1, 1,
                     1, 1, 1, 1, 1, 1, 1, 1, 1,
                     2, 2, 2, 2, 2, 2, 2, 2, 3,
                     2, 2, 2, 2, 2, 2, 2, 2, 3,
                     rep(9, 8), 12, 
                     rep(10, 8), 13, 
                     rep(11, 8), 14, 
                     5, 5, 5, 5, 5, 4, 4, 7, 7, 
                     5, 5, 5, 5, 5, 4, 4, 8, 8,
                     5, 5, 5, 5, 5, 6, NA, 8, 8,  
                     5, 5, 5, 5, 5, 6, NA, 8, 8), 
                   ncol = 9, byrow = TRUE)

footnote <- paste(c("Total No. of Toots: ", nrow(mstdn_data_df),
                    "; Data as of ", format(tail(mstdn_data_df$date, 1), format = "%b %d, %Y")),
                  collapse = "")

title <- toupper("My Mastodon Analytics for 2020")

g <- arrangeGrob(p_date + theme(plot.margin = margin(5, 15, 40, 7),
                                plot.title = element_text(margin = margin(5, 5, -5, 5))), 
            p_wordcount + theme(plot.margin = margin(-25, 10, 5, 5)), 
            p_dist_wordcount + theme(plot.margin = margin(-25, 5, 5, -10)),
            p_type + theme(plot.margin = margin(-65, -30, 5, -45)), 
            p_time +  theme(plot.margin = margin(-40, 5, 5, 10),
                            plot.title = element_text(margin = margin(5, 5, 0, 5))), 
            p_emoji + theme(plot.margin = margin(-22, -30, 5, 0),
                            plot.title = element_text(hjust = 0.55, size = 9)), 
            p_hashtag + theme(plot.margin = margin(-45, 5, 27, 5),
                              plot.title = element_text(size = 9)),
            p_network + theme(plot.margin = margin(-25, -3, -5, -15),
                              plot.title = element_text(hjust = 0.1)),
            p_sondheim$p1 + theme(plot.margin = margin(-2, 10, 29, 5)),
            p_tolkien$p1 + theme(plot.margin = margin(-17, 10, 44, 5)),
            p_malloy$p1 + theme(plot.margin = margin(-32, 10, 59, 5)),
            p_sondheim$p2 + theme(plot.margin = margin(-3, -5, 25, -5)),
            p_tolkien$p2 + theme(plot.margin = margin(-22, 5, 38, -5)),
            p_malloy$p2 + theme(plot.margin = margin(-33, -5, 53, -5)),
            top = textGrob(label = c(title, footnote), x = c(0.04, 0.99), hjust = c(0, 1),
                           gp = gpar(fontfamily = c("Franklin Gothic Demi Cond", frank_med),
                           fontsize = c(13.5, 10), col = "white")),
            bottom = textGrob(label = '@akela', x = 1, hjust = 1, y = 1,
                              gp = gpar(fontfamily = frank_med, 
                              fontsize = 10, col = "white")),
                 layout_matrix = plot_mat)%>%
  cowplot::ggdraw() + 
  theme(plot.background = element_rect(fill= col_bkground, color = NA),
        plot.margin = margin(5, 5, -5, 5))

g

ggsave("mstdn_stat.png", g, width = 7, height = 7.5)
```
